FROM python:3.14.2-slim
LABEL authors="rudig"

RUN apt-get update
RUN apt-get install -y --no-install-recommends tcpdump iproute2 procps
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

CMD ["sh", "-c", "sysctl -w net.ipv4.ip_forward=1 && ip route add 172.16.0.254/32 via 10.0.1.3 && sleep infinity"]
