FROM python:3.14.2-slim
LABEL authors="rudig"

WORKDIR /app

RUN apt-get update
RUN apt-get install -y --no-install-recommends tcpdump iproute2 procps
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

COPY scripts/configure_dut.sh /app/scripts/configure_dut.sh

CMD ["sh", "-c", "/app/scripts/configure_dut.sh && sleep infinity"]
